fix deploy polkadot
soramitsu/fearless-subsquid pull request #18
Opened 2023-02-13 12:11 UTC by f33r0

Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>

2023-02-14 06:03 UTC, wpi86 requested changes

2023-02-14 06:03 UTC, wpi86 commented on Jenkinsfile-subsquid
>                              apt-get install make git curl -y
i think that creating new container for every stage is redundant, it takes time and resources. Also no need to install software on every step, move it to separate step

2023-02-27 07:08 UTC, Cre-eD approved these changes

2023-02-27 07:15 UTC, wpi86 approved these changes

2023-02-27 07:18 UTC, merged